name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy README.md to site
        run: |
          cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/site/README.md
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          branch: gh-pages
          folder: site
